server:
  port: 7005
  servlet:
    context-path: /ware

spring:
  application:
    name: trade-ware
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver               # mysql驱动包 org.h2.Driver
    url: jdbc:mysql://localhost:3306/trade_wms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


  redis:
    port: 6379
    host: 192.168.1.9
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'